### ISSUE TITLE
CDB script

### ISSUE THREAD

**Issue by andrenth** [hokstadconsulting/purecdb#2]
Hi

Do you have a copy of the mentioned perl script that populates the CDB database? I tried to follow the described format with Ruby, but I'm getting a segfault running rum:

```ruby
require 'purecdb'

PureCDB::Writer.open("foo.cdb", mode: 64) do |cdb|
  cdb.store("myuser","*5C224C5BA2FC753C839B9C47CE8D71DFA597EBDD\x000tcp:127.0.0.1\x000")
end
```
```sh
$ sudo ./rum -s tcp:localhost:3307 -s sock:/var/run/mysqld/mysqld.sock -M ./foo.cdb
listening on tcp:localhost:3307
listening on sock:/var/run/mysqld/mysqld.sock
zsh: segmentation fault (core dumped)  sudo ./rum -s tcp:localhost:3307 -s sock:/var/run/mysqld/mysqld.sock -M 

```

strace output doesn't seem very useful:

```
open("./foo.cdb", O_RDONLY)             = 8
fstat(8, {st_mode=S_IFREG|0664, st_size=4342, ...}) = 0
mmap(NULL, 4342, PROT_READ, MAP_SHARED, 8, 0) = 0x7f37fd0f3000
rt_sigaction(SIGUSR1, {0x7f37fccacd50, ~[RTMIN RT_1], SA_RESTORER|SA_RESTART, 0x7f37fc6f14b0}, {SIG_DFL, [], 0}, 8) = 0
epoll_ctl(5, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=7}}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
```

Thanks.

**Comment by vidarh** [comment]
Had not seen this. I'm assuming you've probably found a solution, but in the interest of avoiding similar misunderstandings: I don't know what "rum" is and it's not a very search-friendly name, but assuming that this is a tool that expects CDB database, unless it is a Ruby script that you've modified to use PureCDB, it will *not* be able to read the 64bit format PureCDB uses, as standard CDB only ever uses the 32bit format.

Closing this as it's ancient and I'm asuming this is down to writing with the 64 bit format but trying to read using the 32 bit format, but feel free to open issues if anything else (and I'll hopefully see it sooner).

**Comment by andrenth** [comment]
Huh, I thought I had opened this in the rum repository... no wonder they never replied me.

**Comment by vidarh** [comment]
Ah.. That explains the mention of the perl script etc. But the comment above stands - it likely doesn't understand the 64bit files. If it doesn't understand the 32 bit format, on the other hand, it'd likely mean there'd be a bug in my code...

**Comment by andrenth** [comment]
I can't be sure because I couldn't find in rum's docs the correct format of the CDB entries, which is why I needed their Perl script.

But I have since started using a different project (proxysql), so I haven't had the need to figure it out.
